
package learning.demo.cxf;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-26T15:30:32.579+08:00
 * Generated source version: 3.1.0
 * 
 */
 
public class HelloServer{

    protected HelloServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new learning.demo.cxf.HelloImpl();
        String address = "http://localhost:9090/HelloImplPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new HelloServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 