
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package learning.demo.cxf;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-26T15:30:32.596+08:00
 * Generated source version: 3.1.0
 * 
 */
public class HelloClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://cxf.demo.learning/", "HelloImplService");
        QName portName = new QName("http://cxf.demo.learning/", "HelloImplPort");

        Service service = Service.create(serviceName);
        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
                        "http://localhost:9090/HelloImplPort"); 
        learning.demo.cxf.Hello client = service.getPort(portName,  learning.demo.cxf.Hello.class);
        
        // Insert code to invoke methods on the client here
    }

}